[package]
name = "traits"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { version = "0.1.0", path = "../utils/core", package = "utils" }
crypto_bigint = { git = "ssh://git@github.com/arithmic/crypto_bigint.git", branch = "main", features = [
    "generic-array",
    "zeroize",
] }


